import Head from 'next/head'
import PageInfo from '../src/components/PageInfo'

export default function AboutPage() {
  return (
    <>
      <Head>
        <title>Quem Somos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col justify-center'>
        <PageInfo
          pagePath={["Home", "Quem Somos"]}
          pageTitle="Quem Somos"
          pageSubtitle="A maior rede de tratamento pokemon"
        />

        <div className="flex justify-center mt-6 mb-12">
        <div className="max-w-lg">
          <h4 className="font-extrabold text-2xl">
            O Centro Pokemon
          </h4>

        <div>
          <p>
            Como funciona a cura de um pokemon?
          </p>
        </div>

          <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a nisi ac justo lacinia laoreet. Donec lacinia, lacus at posuere fermentum, libero nunc malesuada libero, nec convallis purus odio eu leo. In augue justo, consequat id turpis at, dignissim viverra magna. Duis vel nulla nec massa pulvinar venenatis non at diam. Duis condimentum egestas nisi, in faucibus lorem mollis bibendum. Morbi ut rutrum magna. Donec aliquet nulla nec leo euismod, vehicula porta tellus facilisis. Suspendisse efficitur feugiat interdum. In pulvinar fringilla elit, a lacinia odio blandit non. Donec cursus rutrum massa eget tempus. Praesent a ex nec quam ornare aliquam. Curabitur lobortis sed dolor vel euismod. Nunc porttitor facilisis magna. Phasellus et tellus nec justo cursus porta quis at enim. 
          </p>
          
          <p>
            Uma tradicao de mais de 20 anos
          </p>

          <p>
          Praesent auctor urna nibh, eget vestibulum orci lobortis vel. In ac nulla aliquet erat tempor gravida vitae vitae lectus. Proin vel elit nunc. Sed dignissim ultrices tellus sed varius. Nam at ligula vitae elit mollis lobortis. In magna lacus, imperdiet in mi eget, tincidunt varius diam. Sed dapibus consequat massa vel gravida. 
          </p>

          <p>
            O melhor para seu pokemon
          </p>

          <p>
          Aenean ac nulla pellentesque, varius ipsum vel, mollis ligula. Etiam nec nisi quis tellus faucibus scelerisque. Curabitur eget suscipit enim. Nullam vel ex pretium, hendrerit erat eu, aliquet turpis. Aenean sed sapien eu leo iaculis imperdiet nec a ante. Ut gravida ante nisi, lacinia tempor magna fringilla ut. Sed massa ipsum, condimentum ac turpis nec, sodales interdum risus. Vivamus ut eros risus. Curabitur ligula nisl, gravida in nibh a, congue blandit orci. 
          </p>

          <p>Alta Tecnologia</p>

          <p>
          Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla nisi urna, vehicula et enim dictum, tincidunt eleifend justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin elementum justo nulla, non convallis neque convallis vel. Curabitur id condimentum arcu. In quis augue a ante interdum fermentum. Fusce rhoncus suscipit orci a porttitor. Mauris vel nibh maximus, maximus risus vel, rhoncus enim. Pellentesque rhoncus dolor bibendum ligula posuere sollicitudin. Praesent finibus pulvinar pulvinar. Nulla malesuada magna nec nunc egestas, id consequat nibh interdum. Nam consectetur metus dolor, tincidunt lacinia orci consequat at. Morbi eget dui dolor. Nulla gravida massa nulla, sit amet feugiat purus porta quis. Quisque auctor vel massa in eleifend. 
          </p>
        </div>
        </div>
      </main>
    </>
  )
}

