import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Centro Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col min-h-screen items-center'>

        <div className='flex justify-center text-white w-full bg-pokemon-hero grow items-center bg-no-repeat bg-cover bg-center'>
          <div className='font-extrabold text-3xl max-w-xl text-center align-middle'>
            Cuidamos bem do seu pokemon, para ele cuidar bem de voce
          </div>
        </div>

      </main>
    </>
  )
}
