import Head from "next/head";
import Image from 'next/image'
import { useEffect, useState } from "react";
import { useRouter } from "next/router";

import PageInfo from "../src/components/PageInfo";

import type { TPayload } from "../src/hooks/schedule";
import Button from "../src/components/Button";

export default function SubmitPage() {
  const router = useRouter();
  const successSubmit: string | null = sessionStorage.getItem("successSubmit");
  const [success, setSuccess] = useState(false);
  const [message, setMessage] = useState("");

  useEffect(() => {
    if (successSubmit) {
      setSuccess(true);
      const payload: TPayload = JSON.parse(successSubmit);
      const [hour, minutes] = payload.time.split(":");
      setMessage(
        `Seu agendamento para dia ${payload.date}, às ${hour}h${minutes}m, para ${payload.pokemonsAmount}x pokémons foi realizado com sucesso!`
      );
    } else {
      setSuccess(false);
      setMessage(
        "Infelizmente não foi possível salvar seu agendamento, por favor tente um novo agendamento!"
      );
    }
  }, [successSubmit]);

  return (
    <>
      <Head>
        <title>Agendar Consulta</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col justify-center'>
        <PageInfo
          pagePath={["Home", "Agendar Consulta"]}
          pageTitle="Agendar Consulta"
          pageSubtitle="Recupere seus pokémons em 5 segundos"
        />

        <div className='flex justify-center w-full items-center min-h-screen'>
          <div className="rounded flex flex-col items-center p-9 border border-solid border-red-600 bg-stone-50 justify-center max-w-sm">
            <h1 className="text-xl font-bold text-center mb-4">
              {success ? "Consulta Agendada" : "Houve um problema no agendamento"}
            </h1>

            <Image
              alt="modal-ico"
              src={success ? "/images/check.svg" : "/images/warning.svg"}
              width={35}
              height={35}
            />

            <div className="text-sm text-center font-normal text-gray-800 my-4">
              { message }
            </div>

            <Button onClick={() => router.push("/schedule")}>
              Fazer novo Agendamento
            </Button>
          </div>
        </div>
      </main>
    </>
  )
}
